export enum KYCStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  INFO_REQUESTED = 'INFO_REQUESTED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
}

export const ALL_KYC_STATUSES = [
  KYCStatus.DRAFT,
  KYCStatus.SUBMITTED,
  KYCStatus.APPROVED,
  KYCStatus.REJECTED,
  KYCStatus.INFO_REQUESTED,
  KYCStatus.REVISION_REQUESTED, // for re submut of data
];