export enum UserRole {
  BUYER = 'BUYER',
  SELLER = 'SELLER',
  ADMIN = 'ADMIN',
  LOGISTIC = 'LOGISTIC',
  '3PL' = '3PL',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

// ❌ REMOVED: Duplicate KycStatus enum - Use KYCStatus from modules/kyc/kyc-status.constants.ts instead

export enum RfqStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  AWARDED = 'AWARDED', // ✅ Added to match frontend
  EXPIRED = 'EXPIRED',
}

export enum QuoteStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  NEGOTIATING = 'NEGOTIATING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum OrderStatus {
  CREATED = 'CREATED',
  CONFIRMED = 'CONFIRMED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  PAID = 'PAID',
  DISPATCH_PREP = 'DISPATCH_PREP',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  GST_CERTIFICATE = 'GST_CERTIFICATE',
  PAN_CERTIFICATE = 'PAN_CERTIFICATE',
  CANCELLED_CHEQUE = 'CANCELLED_CHEQUE',
  BANK_LETTER = 'BANK_LETTER',                 // ✅ Added
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',       // ✅ Added
  FACTORY_LICENSE = 'FACTORY_LICENSE',
  INCORPORATION_CERT = 'INCORPORATION_CERT',   // ✅ Added
  QA_CERTIFICATE = 'QA_CERTIFICATE',           // ✅ Added
  COMPANY_PAN = 'COMPANY_PAN',                 // ✅ Added
}
